module.exports = [
  {
    name: 'Sodium Chloride (NaCl)',
    sku: 'NaCl-AR-001',
    description: 'Analytical reagent grade sodium chloride, ≥99.5% purity',
    category: 'Inorganic Salts',
    baseUnit: 'g',
    basePricePerUnitINR: 0.25,
    stockQty: 50000,
    lowStockThreshold: 1000,
  },
  {
    name: 'Ethanol Absolute (C₂H₅OH)',
    sku: 'EtOH-ABS-002',
    description: 'Absolute ethanol, ≥99.9% anhydrous, HPLC grade',
    category: 'Solvents',
    baseUnit: 'mL',
    basePricePerUnitINR: 0.085,
    stockQty: 100000,
    lowStockThreshold: 5000,
  },
  {
    name: 'Hydrochloric Acid (HCl) 37%',
    sku: 'HCl-37-003',
    description: 'Concentrated hydrochloric acid, 37% w/w, AR grade',
    category: 'Acids',
    baseUnit: 'mL',
    basePricePerUnitINR: 0.12,
    stockQty: 25000,
    lowStockThreshold: 2000,
  },
  {
    name: 'Glucose Anhydrous (D-Glucose)',
    sku: 'GLU-AH-004',
    description: 'D-(+)-Glucose anhydrous, ≥99.5%, suitable for cell culture',
    category: 'Sugars & Carbohydrates',
    baseUnit: 'g',
    basePricePerUnitINR: 1.80,
    stockQty: 10000,
    lowStockThreshold: 500,
  },
  {
    name: 'Sulfuric Acid (H₂SO₄) 98%',
    sku: 'H2SO4-98-005',
    description: 'Concentrated sulfuric acid, 98% w/w, analytical reagent',
    category: 'Acids',
    baseUnit: 'mL',
    basePricePerUnitINR: 0.09,
    stockQty: 20000,
    lowStockThreshold: 1000,
  },
  {
    name: 'Acetone (CH₃COCH₃)',
    sku: 'ACE-HPLC-006',
    description: 'Acetone HPLC grade, ≥99.9% purity, low water content',
    category: 'Solvents',
    baseUnit: 'mL',
    basePricePerUnitINR: 0.07,
    stockQty: 50000,
    lowStockThreshold: 3000,
  },
  {
    name: 'Potassium Permanganate (KMnO₄)',
    sku: 'KMnO4-AR-007',
    description: 'Potassium permanganate, AR grade, ≥99.0% purity',
    category: 'Oxidizing Agents',
    baseUnit: 'g',
    basePricePerUnitINR: 0.95,
    stockQty: 5000,
    lowStockThreshold: 250,
  },
  {
    name: 'Methanol (CH₃OH)',
    sku: 'MeOH-HPLC-008',
    description: 'Methanol HPLC grade, ≥99.9% purity, UV cutoff 205 nm',
    category: 'Solvents',
    baseUnit: 'mL',
    basePricePerUnitINR: 0.065,
    stockQty: 75000,
    lowStockThreshold: 5000,
  },
  {
    name: 'Ammonium Chloride (NH₄Cl)',
    sku: 'NH4Cl-AR-009',
    description: 'Ammonium chloride, analytical reagent grade, ≥99.5%',
    category: 'Inorganic Salts',
    baseUnit: 'g',
    basePricePerUnitINR: 0.35,
    stockQty: 20000,
    lowStockThreshold: 500,
  },
  {
    name: 'Borosilicate Glass Beakers 250mL',
    sku: 'BGK-250-010',
    description: 'Borosilicate 3.3 glass beaker, 250mL capacity, with spout',
    category: 'Glassware',
    baseUnit: 'unit',
    basePricePerUnitINR: 185,
    stockQty: 200,
    lowStockThreshold: 10,
  },
  {
    name: 'Sodium Hydroxide (NaOH) Pellets',
    sku: 'NaOH-PL-011',
    description: 'Sodium hydroxide pellets, AR grade, ≥98% purity',
    category: 'Bases',
    baseUnit: 'g',
    basePricePerUnitINR: 0.42,
    stockQty: 30000,
    lowStockThreshold: 1000,
  },
  {
    name: 'Isopropyl Alcohol (IPA) 99.9%',
    sku: 'IPA-999-012',
    description: 'Isopropyl alcohol / 2-Propanol, electronics grade, ≥99.9%',
    category: 'Solvents',
    baseUnit: 'mL',
    basePricePerUnitINR: 0.078,
    stockQty: 60000,
    lowStockThreshold: 4000,
  },
  {
    name: 'Aspirin (Acetylsalicylic Acid)',
    sku: 'ASA-API-013',
    description: 'Active Pharmaceutical Ingredient, USP grade powder, ≥99.0% purity',
    category: 'Active Pharmaceutical Ingredients',
    baseUnit: 'g',
    basePricePerUnitINR: 1.45,
    stockQty: 25000,
    lowStockThreshold: 2000,
  },
  {
    name: 'Paracetamol (Acetaminophen)',
    sku: 'PARA-API-014',
    description: 'Acetaminophen fine powder, BP/USP grade, analgesics intermediate',
    category: 'Active Pharmaceutical Ingredients',
    baseUnit: 'g',
    basePricePerUnitINR: 0.95,
    stockQty: 40000,
    lowStockThreshold: 5000,
  },
  {
    name: 'Nitric Acid (HNO₃) 68%',
    sku: 'HNO3-68-015',
    description: 'Concentrated nitric acid, 68% w/w, analytical reagent grade',
    category: 'Acids',
    baseUnit: 'mL',
    basePricePerUnitINR: 0.18,
    stockQty: 30000,
    lowStockThreshold: 3000,
  },
  {
    name: 'Calcium Carbonate (CaCO₃)',
    sku: 'CaCO3-AR-016',
    description: 'Calcium carbonate precipitated, analytical reagent grade',
    category: 'Inorganic Salts',
    baseUnit: 'g',
    basePricePerUnitINR: 0.15,
    stockQty: 75000,
    lowStockThreshold: 5000,
  },
  {
    name: 'Disposable Syringes 5mL',
    sku: 'SYR-5ML-017',
    description: 'Sterile single-use disposable syringes, luer slip, with needle',
    category: 'Medical Supplies',
    baseUnit: 'unit',
    basePricePerUnitINR: 4.50,
    stockQty: 5000,
    lowStockThreshold: 500,
  },
  {
    name: 'N95 Face Masks',
    sku: 'MASK-N95-018',
    description: 'Particulate respirator mask, high filtration efficiency ≥95%',
    category: 'Medical Supplies',
    baseUnit: 'unit',
    basePricePerUnitINR: 25.00,
    stockQty: 1200,
    lowStockThreshold: 200,
  },
];
